<a href="https://colab.research.google.com/github/ricardogiorgiano/FormulariodeLogin/blob/main/Aula_Pr%C3%A1tica_1_LP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
NUMPY - 1º Abrir documentção


In [3]:
import numpy as np
num_elementos = 100000000
# lista_elementos = []
# for x in range (num_elementos):
#   lista_elementos.append(x)
# print(lista_elementos[-1])
array_elementos = np.arange(num_elementos)
print (array_elementos[-1])


99999999


Qual a diferença do array NUMPY para list in python


# NUMPY - 3º Arrays em numpy

In [19]:

array_teste = np.array([0,1,2,3,4,5,6,7,8,9])
print(f'Criação de array numpy utilizando o método .array:\n{np.array([0,1,2,3,4,5,6,7,8,9])}\n')
print(f'Criação de array numpy utilizando o método .ones:\n{np.ones([10])}\n')
print(f'Criação de array numpy utilizando o método .empty:\n{np.empty(12)}\n')
print(f'Criação de array numpy utilizando o método .arange:\n{np.arange(101)}\n')
print(f'Criação de array numpy utilizando o método .linspace:\n{np.linspace(0, 100, num = 101)}\n')







Criação de array numpy utilizando o método .array:
[0 1 2 3 4 5 6 7 8 9]

Criação de array numpy utilizando o método .ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Criação de array numpy utilizando o método .empty:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Criação de array numpy utilizando o método .arange:
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]

Criação de array numpy utilizando o método .linspace:
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  

# NUMPY 4º  A importancia de definir o tipo de dados;

In [20]:
import numpy as np

num_elementos = 100000000
array_elementos = np.zeros(num_elementos, dtype = np.int8)

